# Generated by Django 5.0.6 on 2024-05-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='PreMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('unwashed', 'Unwashed'), ('boiled', 'Boiled')], default='boiled', max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'PreMethod',
                'verbose_name_plural': 'PreMethods',
            },
        ),
        migrations.CreateModel(
            name='TabaccoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'TabaccoTag',
                'verbose_name_plural': 'TabaccoTags',
            },
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('leaf', models.CharField(max_length=120, verbose_name='leaf')),
                ('composition', models.CharField(max_length=120, verbose_name='composition')),
                ('strength', models.CharField(choices=[('light', 'Light'), ('hard', 'Hard')], default='hard', max_length=120, verbose_name='strength')),
                ('taste', models.CharField(max_length=120, verbose_name='taste')),
                ('type', models.CharField(choices=[('mint', 'Mint'), ('mix', 'Mix'), ('flavor drinks', 'Flavor drinks'), ('spicy', 'Spicy')], default='mix', max_length=120, verbose_name='type')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='tobacco.country', verbose_name='country')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco.manufacturer', verbose_name='manufacturer')),
                ('preparation', models.ManyToManyField(related_name='tobaccos', to='tobacco.premethod', verbose_name='preparation')),
                ('tag', models.ManyToManyField(blank=True, to='tobacco.tabaccotag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tobacco',
                'verbose_name_plural': 'Tobaccos',
            },
        ),
        migrations.CreateModel(
            name='TobaccoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Photo')),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tobacco.tobacco', verbose_name='Tobacco')),
            ],
            options={
                'verbose_name': 'Tobacco Image',
                'verbose_name_plural': 'Tobacco Images',
            },
        ),
    ]
