# Generated by Django 5.0.6 on 2024-05-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobaccoimages',
            name='tobacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobacco_images', to='tobacco.tobacco', verbose_name='Tobacco'),
        ),
    ]
