# Generated by Django 5.0.6 on 2024-05-13 11:31

import django.core.validators
import django.db.models.deletion
import lounge.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('price', models.CharField(max_length=120, verbose_name='Price')),
                ('rate_google', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('rate_yandex', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('phone_number', models.CharField(max_length=20, validators=[lounge.utils.validate_phone_number], verbose_name='phone number')),
                ('work_time', models.DateTimeField(verbose_name='work time')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Lounge',
                'verbose_name_plural': 'Lounges',
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Metro',
                'verbose_name_plural': 'Metro',
            },
        ),
        migrations.CreateModel(
            name='LoungeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge', to='lounge.lounge', verbose_name='lounge')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Lounge Images',
                'verbose_name_plural': 'Lounge Images',
            },
        ),
        migrations.AddField(
            model_name='lounge',
            name='metro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounge.metro', verbose_name='Metro'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=50)),
                ('url', models.URLField()),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounge.lounge')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
