# Generated by Django 5.0.6 on 2024-05-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='rate_google',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг Google'),
        ),
        migrations.AlterField(
            model_name='lounge',
            name='rate_yandex',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг Yandex'),
        ),
    ]
