# Generated by Django 5.0.6 on 2024-05-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0003_alter_loungeimages_lounge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='metro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro', to='lounge.metro', verbose_name='Metro'),
        ),
    ]
