# Generated by Django 5.0.6 on 2024-05-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='strength',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strength', to='mix.strength', verbose_name='strength'),
        ),
    ]
