# Generated by Django 5.0.6 on 2024-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0002_mix_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='percentage',
            field=models.IntegerField(verbose_name='percentage'),
        ),
    ]
