# Generated by Django 5.0.6 on 2024-05-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0003_alter_strength_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength', to='mix.strength', verbose_name='strength'),
        ),
    ]
